name: azabraao-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/free
  - defaults
dependencies:
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pandas=0.25.0
  - pandas-datareader=0.7.0
  - scikit-learn
  - seaborn

 